// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgqhmzbmvbssebhksupc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZncWhtemJtdmJzc2ViaGtzdXBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2NjU0NzAsImV4cCI6MjA3ODI0MTQ3MH0.ljMx-LjhWyVdGzKzBiqHfUD4xszNH9vUpbXqIUGegvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});